# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Proje dosyalarını kopyala ve restore et
COPY EduMicroService.Shared/*.csproj EduMicroService.Shared/
COPY EduMicroService.Basket.Api/*.csproj EduMicroService.Basket.Api/

RUN dotnet restore EduMicroService.Basket.Api/*.csproj

# Tüm kaynak kodları kopyala
COPY . .

# Publish işlemi
RUN dotnet publish EduMicroService.Basket.Api/*.csproj -c Release -o out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
EXPOSE 80

# Published files'ları kopyala
COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "EduMicroService.Basket.Api.dll"]