@baseAddress = http://localhost:5198
@categoryId = 08dd7600-6cd4-a0a7-0015-5d43bf9f0000
@courseId = 08dd818f-8132-9208-74d4-ddb7ab3f0000
@userId = ab3f0000-ddb7-74d4-8f9b-08dd81d4d918


GET {{baseAddress}}/api/v1.0/categories
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Bigisayar"
}
###
GET {{baseAddress}}/api/Categories/{{categoryId}}
Accept: application/json
###
POST {{baseAddress}}/api/Courses/
Accept: application/json
Content-Type: application/json
{
  "name": "New Course 2",
  "description": "This is a new course",
  "price": 100,
  "imageUrl": "images/bilgisyar.png",
  "categoryId": "{{categoryId}}"
}
###
PUT {{baseAddress}}/api/Courses/
Accept: application/json
Content-Type: application/json
{
  "id": "{{courseId}}",
  "name": "New Course Update",
  "description": "This is a new course  Update",
  "price": 333,
  "imageUrl": "images/bilgisyar.png  Update",
  "categoryId": "{{categoryId}}"
}
###
GET {{baseAddress}}/api/v1/Courses/
Accept: application/json
###
GET {{baseAddress}}/api/v1/Courses/{{courseId}}
Accept: application/json
###
DELETE {{baseAddress}}/api/Courses/{{courseId}}
Accept: application/json
###
GET {{baseAddress}}/api/Courses/User/{{userId}}
Accept: application/json
###